# Generated by Django 3.2.13 on 2022-07-04 01:31

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0018_add_waffle_flag_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassedLearnerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_id', models.IntegerField()),
                ('data', jsonfield.fields.JSONField()),
                ('follow_up_date', models.DateField()),
            ],
        ),
        migrations.AddIndex(
            model_name='passedlearnerevent',
            index=models.Index(fields=['follow_up_date'], name='grades_pass_follow__b5036f_idx'),
        ),
        migrations.AddIndex(
            model_name='passedlearnerevent',
            index=models.Index(fields=['created'], name='grades_pass_created_4aa5f7_idx'),
        ),
    ]
